name: integrated_rgb_thermal_ortho
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  
  - blas=*=openblas
  - bottleneck
  - certifi
  - cffi
  - click>=8.0
  - colorama
  - contourpy
  - cryptography
  - cycler
  - expat
  - freetype
  - fsspec
  - gdal>=3.4
  - geopandas>=0.12
  - geos>=3.8
  - glib
  - hdf5
  - icc_rt
  - imageio
  - intel-openmp
  - jinja2
  - joblib
  - jpeg
  - kiwisolver
  - krb5
  - lerc
  - libcurl
  - libdeflate
  - libffi
  - libpng
  - libspatialindex
  - libsqlite
  - libtiff
  - libwebp-base
  - libxml2
  - lz4-c
  - markupsafe
  - mkl
  - mkl-service
  - mpmath
  - networkx
  - numpy>=1.21,<2.0
  - openjpeg
  - openssl
  - packaging
  - pandas>=1.5
  - pcre2
  - pillow>=9.0
  - pip
  - proj>=9.0
  - psutil
  - pyproj>=3.3
  - pysocks
  - python-dateutil
  - pywavelets
  - pyyaml>=6.0
  - qhull
  - requests>=2.28
  - rtree
  - scikit-image>=0.19
  - scikit-learn>=1.1
  - scipy>=1.8
  - setuptools
  - shapely>=1.8
  - six
  - snappy
  - sqlite
  - sympy
  - tbb
  - threadpoolctl
  - tk
  - typing_extensions
  - ucrt
  - unicodedata2
  - urllib3
  - vc>=14.2
  - vs2015_runtime
  - wheel
  - win_inet_pton
  - xz
  - zipp
  - zlib
  - zstd
  
  - pip:
    - affine>=2.3
    - aiohttp>=3.8
    - aiosignal
    - albumentations>=1.3
    - attrs>=22.0
    - beautifulsoup4>=4.11
    - charset-normalizer
    - cloudpickle
    - deepforest>=1.2
    - edt
    - exifread
    - fiona>=1.8
    - flask>=2.0
    - flatbuffers
    - fpdf2
    - frozenlist
    - gdown
    - idna
    - imagecodecs
    - imagesize
    - importlib-metadata
    - itsdangerous
    - laspy
    - lightning>=2.0
    - lightning-utilities
    - lxml
    - munch
    - multidict
    - odmexifread
    - onnxruntime>=1.12
    - opencv-python>=4.7
    - opencv-python-headless>=4.7
    - protobuf>=4.21
    - pyodm>=1.5
    - pyqt5>=5.15
    - pyreadline3
    - pysolar
    - pytest
    - python-dotenv
    - python-utils
    - pytorch-lightning>=2.0
    - pytz
    - qudida
    - rasterio>=1.2
    - rawpy
    - repoze-lru
    - requests-toolbelt
    - slidingwindow
    - snowballstemmer
    - snuggs
    - soupsieve
    - sphinx
    - sphinxcontrib-applehelp
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml
    - torch>=2.0
    - torchaudio>=2.0
    - torchmetrics>=0.11
    - torchvision>=0.15
    - tqdm>=4.64
    - werkzeug>=2.0
    - xmltodict
    - yarl
